---
- name: Get all regions
  amazon.aws.aws_region_info:
    region: "us-east-2"
  register: allregions

- name: Loop over all ec2 regions
  ansible.builtin.include_tasks:
    file: stop_ec2.yml
  loop: "{{ allregions.regions }}"
  loop_control:
    label: "{{ item.region_name }}"
