---
- name: Create AWS Detailed Report
  hosts: localhost
  tasks:

    - name: Gather AWS Detailed info
      ansible.builtin.include_role:
        name: aws_retrieve_info

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_aws
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
