---
- name: Loop over all ec2 regions
  ansible.builtin.include_tasks:
    file: retrieve_info.yml
  loop: "{{ ec2_regions }}"

- name: Grab boto version
  ansible.builtin.pip:
    name: boto3
  register: register_boto3_version
  check_mode: true

- name: Grab information about AWS user
  amazon.aws.aws_caller_info:
  register: whoami

- name: Save username of AWS user and boto3 version
  ansible.builtin.set_fact:
    aws_user: '{{ whoami.arn.split("/")[-1] }}'
    boto3_version: >-
      {{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') | default('unknown') }}
