---
- name: Build the Schedule for Stopping AWS instances for {{ owner }} in {{ env }}
  ansible.controller.schedule:
    name: Park AWS instances for {{ owner }} in {{ env }}
    state: present
    unified_job_template: AWSParking-Stop
    rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=stop_date_time, timezone='GMT', every=repetition | int) }}"
    extra_data:
      owner: "{{ owner }}"
      env: "{{ env }}"

- name: Build the Schedule for Starting AWS instances for {{ owner }} in {{ env }}
  ansible.controller.schedule:
    name: UnPark AWS instances for {{ owner }} in {{ env }}
    state: present
    unified_job_template: AWSParking-Start
    rrule: "{{ query('ansible.controller.schedule_rrule', frequency, start_date=start_date_time, timezone='GMT', every=repetition | int) }}"
    extra_data:
      owner: "{{ owner }}"
      env: "{{ env }}"
